<?php
return [
    "notes"=>[
        "name"=>"notes",
        "user"=>"root",
        "pass"=>"",
        "host"=>"127.0.0.1",
        "port"=>"3306",
        "charset"=>"utf8"
    ],
    "book_shop"=>[
        "name"=>"book_shop",
        "user"=>"root",
        "pass"=>"",
        "host"=>"127.0.0.1",
        "port"=>"3306",
        "charset"=>"utf8"
    ],
    ];